FROM golang:1.24-alpine

RUN go install github.com/air-verse/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

WORKDIR /go/src

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download && go mod verify

CMD [ "air" ]
